const swaggerAutogen = require('swagger-autogen')()


const doc = {
  info: {
      version: "1.0.0",
      title: "Train Pusher API",
      description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:8080",
  basePath: "/api/v1",
  schemes: ['http'],
  consumes: ['text/plain'],
  produces: ['text/plain', "application/json"]
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./src/controllers/*.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(async () => {
  await import('./src/main.js')
})
